### ISSUE TITLE
typings.json" is missing on npm install

### ISSUE THREAD

**Issue by amalshehu** [jiayihu/billy#1]

**Comment by jiayihu** [comment]
@amalshehu Thanks, I removed the `postinstall` script (:

**Comment by amalshehu** [comment]
@jiayihu That's coolAny fix for this issue?

**Comment by jiayihu** [comment]
What do you mean? Should be already fixed by https://github.com/jiayihu/billy/commit/537c74df3339711371f7308b8538275e56a61ddc

**Comment by amalshehu** [comment]
This is the error i'm facing now. Any suggestions?
> webpack-dev-server --inline --config webpack.config.js

module.js:471
    throw err;
    ^

Error: Cannot find module './env.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/amalshehu/Code/billy/webpack.config.js:2:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular2@1.0.0 start: `webpack-dev-server --inline --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2@1.0.0 start script 'webpack-dev-server --inline --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2
npm ERR! There is likely additional logging output above.

**Comment by jiayihu** [comment]
You're right, I'm using some free API services which requires registration and private API keys. I keep them in a file named `env.json` which is not versioned by git.
I fixed now pushing an example of `env.json` but you will need to create an account yourself. I added instructions in README. Without the API keys you should be able to run the application anyway, but some parts won't work like countries autosuggestion in forms.
